import React, { useEffect, useState } from "react";
import Loading from "./Loading";
import { useAppContext } from "../context/AppContext";
import toast from "react-hot-toast";

function Community() {
  const [images, setImages] = useState([]);
  const [loading, setLoading] = useState(true);

  const { axios } = useAppContext();

  const fetchImages = async () => {
    try {
      const { data } = await axios.get("/api/user/published-images");

    

      if (data.success) {
        setImages(data.images);
      } else {
        toast.error(data.message);
      }
    } catch (error) {
      console.error(error);
      toast.error(error.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchImages();
  }, []);

  if (loading) return <Loading />;

  return (
    <div className="p-6 pt-12 xl:px-12 2xl:px-20 w-full max-w-7xl mx-auto h-full overflow-y-auto">
      <h2 className="text-xl font-semibold mb-6 text-gray-800 dark:text-purple-100">
        Community Images
      </h2>

      {images.length > 0 ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">
          {images.map((item, index) => (
            <a
              key={index}
              href={item.imageUrl}
              target="_blank"
              rel="noreferrer"
              className="relative group block rounded-lg overflow-hidden border border-amber-200 dark:border-purple-700 shadow-sm hover:shadow-md transition-all"
            >
              <img
                src={item.imageUrl}
                alt={`Generated by ${item.userName}`}
                className="w-full h-52 object-cover group-hover:scale-105 transition-transform duration-300"
                loading="lazy"
              />

              <div className="absolute bottom-0 left-0 right-0 bg-black/60 text-white text-xs p-2 opacity-0 group-hover:opacity-100 transition-opacity">
                Created by {item.userName}
              </div>
            </a>
          ))}
        </div>
      ) : (
        <p className="text-center text-gray-600 dark:text-pink-200 mt-10">
          No images available
        </p>
      )}
    </div>
  );
}

export default Community;